### ISSUE TITLE
Need help with selenium

### ISSUE THREAD

**Issue by Vipth** [VrtK/SimpleMMO-Bot#1]
When I try to run the program I get this error:

`C:\Users\Vipth>C:\Users\Vipth\Desktop\SimpleMMO-Bot-main\SimpleMMO-Bot-main\SimpleMMO.py
Traceback (most recent call last):
  File "C:\Users\Vipth\Desktop\SimpleMMO-Bot-main\SimpleMMO-Bot-main\SimpleMMO.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'`

Any idea on how to fix this? I've tried uninstalling and reinstalling selenium, and it still won't work.

**Comment by VrtK** [comment]
you should install selenium first,
pip install selenium and make sure you have the correct driver exe

**Comment by Vipth** [comment]
I was able to fix the issue using `python -m ensurepip`, follow by `python -m pip install selenium` & `python -m pip install chromedriver_autoinstaller`. Not sure why I had to do install them this way, but it fixed my issue.
